interval_secs = 60
interval_secs_on_ac = 60
timezone = "Local"
log_dir = "~/.local/state/battery-logger"
log_file = "battery.csv"
max_lines = 2000
trim_buffer = 100
max_charge_percent = 100

# Day/Night visualization settings
day_color_number = 237    # Dark gray for day (darker but still distinguishable)
night_color_number = 0    # True black for night (pitch black)
day_start_hour = 7        # 7 AM - when day starts
day_end_hour = 19         # 7 PM - when night starts