interval_secs = 60
interval_secs_on_ac = 60
timezone = "Local"
log_dir = "~/.local/state/battery-logger"
log_file = "battery.csv"
max_lines = 2000
trim_buffer = 100
max_charge_percent = 100

# Day/Night visualization settings
day_color_number = -1     # Default terminal foreground color for day
night_color_number = 234  # Very dark gray for night
day_start_hour = 7        # 7 AM - when day starts
day_end_hour = 19         # 7 PM - when night starts

# Zoom settings
max_window_zoom = 10      # Maximum zoom window in days

# Suspend/shutdown detection settings
suspend_gap_minutes = 5   # Consider data gaps >= this duration as suspend/shutdown events